import { NgModule } from '@angular/core';
import {
  IonAccordion,
  IonAccordionGroup,
  IonButton,
  IonButtons,
  IonCheckbox,
  IonContent,
  IonDatetime,
  IonDatetimeButton,
  IonFooter,
  IonHeader,
  IonIcon,
  IonImg,
  IonInput,
  IonItem,
  IonLabel,
  IonMenu,
  IonMenuButton,
  IonModal,
  IonPopover,
  IonRadio,
  IonRadioGroup,
  IonRippleEffect,
  IonSelect,
  IonSelectOption,
  IonTabBar,
  IonTabButton,
  IonTabs,
  IonTextarea,
  IonTitle,
  IonToggle,
  IonToolbar,
  IonGrid,
  IonRow,
  IonCol,
} from '@ionic/angular/standalone';

const imports = [
  IonAccordion,
  IonAccordionGroup,
  IonButton,
  IonButtons,
  IonCheckbox,
  IonContent,
  IonDatetime,
  IonDatetimeButton,
  IonFooter,
  IonHeader,
  IonIcon,
  IonImg,
  IonInput,
  IonItem,
  IonLabel,
  IonMenu,
  IonMenuButton,
  IonModal,
  IonPopover,
  IonRadio,
  IonRadioGroup,
  IonRippleEffect,
  IonSelect,
  IonSelectOption,
  IonTabBar,
  IonTabButton,
  IonTabs,
  IonTextarea,
  IonTitle,
  IonToggle,
  IonToolbar,
  IonGrid,
  IonRow,
  IonCol,
];

@NgModule({
  imports: [...imports],
  exports: [...imports],
})
export class IonicSharedModule {}
