import { Component } from '@angular/core';
import { IonApp, IonRouterOutlet } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  add,
  addCircle,
  arrowBack,
  arrowRedo,
  attach,
  barcodeOutline,
  build,
  calendarOutline,
  call,
  camera,
  chatboxEllipsesOutline,
  checkmark,
  checkmarkCircle,
  checkmarkCircleOutline,
  chevronDown,
  chevronForward,
  close,
  construct,
  createOutline,
  documentsOutline,
  documentTextOutline,
  download,
  ellipse,
  ellipsisHorizontalCircleOutline,
  ellipsisVertical,
  eye,
  eyeOff,
  eyeOffOutline,
  eyeOutline,
  gitBranchOutline,
  gridOutline,
  helpCircleOutline,
  home,
  idCardOutline,
  imageOutline,
  leaf,
  lockClosed,
  logoFacebook,
  logOutOutline,
  logoWhatsapp,
  mail,
  mailOutline,
  menu,
  openOutline,
  peopleOutline,
  person,
  personAddOutline,
  personCircle,
  personOutline,
  phonePortraitOutline,
  play,
  playSkipForward,
  playSkipForwardCircle,
  readerOutline,
  remove,
  search,
  send,
  settings,
  square,
  stopwatchOutline,
  timeOutline,
  timerOutline,
  trash,
  trashOutline,
  triangle,
} from 'ionicons/icons';
import { register } from 'swiper/element/bundle';
import { SidebarMenuComponent } from './components/sidebar-menu/sidebar-menu.component';

register();

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss'],
  standalone: true,
  imports: [IonApp, IonRouterOutlet, SidebarMenuComponent],
})
export class AppComponent {
  constructor() {
    addIcons({
      add,
      addCircle,
      arrowBack,
      arrowRedo,
      attach,
      barcodeOutline,
      build,
      calendarOutline,
      call,
      camera,
      chatboxEllipsesOutline,
      checkmark,
      checkmarkCircle,
      checkmarkCircleOutline,
      chevronDown,
      chevronForward,
      close,
      construct,
      createOutline,
      documentsOutline,
      documentTextOutline,
      download,
      ellipse,
      ellipsisHorizontalCircleOutline,
      ellipsisVertical,
      eye,
      eyeOff,
      eyeOffOutline,
      eyeOutline,
      gitBranchOutline,
      gridOutline,
      helpCircleOutline,
      home,
      idCardOutline,
      imageOutline,
      leaf,
      lockClosed,
      logoFacebook,
      logOutOutline,
      logoWhatsapp,
      mail,
      mailOutline,
      menu,
      openOutline,
      peopleOutline,
      person,
      personAddOutline,
      personCircle,
      personOutline,
      phonePortraitOutline,
      play,
      playSkipForward,
      playSkipForwardCircle,
      readerOutline,
      remove,
      search,
      send,
      settings,
      square,
      stopwatchOutline,
      timeOutline,
      timerOutline,
      trash,
      trashOutline,
      triangle,
    });
  }
}
